name: Lua Lint

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Lua
      run: |
        sudo apt-get update
        sudo apt-get install -y lua5.3 luarocks
    
    - name: Install luacheck
      run: |
        sudo luarocks install luacheck
    
    - name: Run luacheck
      run: |
        luacheck . --exclude-files .install --exclude-files .luarocks --no-unused-args --no-max-line-length || true
    
    - name: Validate info.json
      run: |
        python3 -m json.tool info.json > /dev/null
        echo "info.json is valid JSON"
